version: '3'
services:
  web:
    image: 'pcr-internal.puppet.net/infracore/elsabuilder_web'
    ports:
    - "5000:5000"
    expose:
    - "5000"
    environment:
    - CELERY_BROKER_URL=pyamqp://guest@rabbitmq//
    - CELERY_RESULT_BACKEND=database
    - CELERY_RESULT_DBURI=couchdb://couchdb:5984
    links:
    - rabbitmq
    - couchdb
  worker:
    image: 'pcr-internal.puppet.net/infracore/elsabuilder_worker'
    environment:
    - CELERY_BROKER_URL=pyamqp://guest@rabbitmq//
    - CELERY_RESULT_BACKEND=database
    - CELERY_RESULT_DBURI=couchdb://couchdb:5984
    links:
    - rabbitmq
    - couchdb
  rabbitmq:
    image: rabbitmq
  couchdb:
    image: couchdb
    ports:
    - "5984:5984"
