FROM infracore/elsabuilder_base

ADD ssh/config /root/.ssh/config
ADD ssh/id_rsa-acceptance /root/.ssh/id_rsa-acceptance
ADD ssh/id_rsa-elsabuilder /root/.ssh/id_rsa
ADD ssh/id_rsa-elsabuilder.pub /root/.ssh/id_rsa.pub
