FROM pcr-internal.puppet.net/infracore/elsabuilder_base

ENV code /code
WORKDIR $code

ENV PYTHONPATH="${code}"
ADD . $code

ADD .vmfloaty.yml /root/.vmfloaty.yml

RUN pip install -r service-requirements.txt

ENTRYPOINT gunicorn -w 4 -b 0.0.0.0:5000 web.frankenbuild:app
