FROM ruby:2.4-stretch

RUN gem install --no-ri --no-rdoc bundle vmfloaty

RUN set -ex \
  && apt-get update \
  && apt-get install -y --no-install-recommends python-dev python-pip python-setuptools python-wheel \
  && rm -rf /var/lib/apt/lists/*
